---
title: "Cat meta learner set creation"
output: html_document
date: "2024-06-23"
Notes: " This script is inteneded to create the meta learner test/train set for the cat stacking model"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project")

```

Load the packages
```{r}
library(dplyr)
library(readr)
library(tidyverse)
library(xgboost)
library(caret)
library(caTools)
```
Load the functions
```{r}
# Function to map factor levels to weights
feature_digit_function <- function(factors) {
  sapply(factors, function(x) selected_weights[as.numeric(x)])
}

```


Set the constant variables 
```{r}
# The RNA list
rna_list <- list(
  transcripts_per_million = "tpm",
  scalled_transcripts_per_million = "scld_tpm",
  log_scalled_transcripts_per_million = "log_scld_tpm",
  log_transcripts_per_million = "log_tpm",
  expected_counts = "exp",
  scalled_expected_counts = "scld",
  log_expected_counts = "log",
  log_scalled_expected_counts = "log_scld"
)

# The path to the RNA sets
rna_data_path <- "Data/RNA_Data/Model_Input/Train/"

# The CIN response features
chr_cnv <- read_tsv(
  "Data/CIN_Features/CNV_Data/PANCAN_ArmCallsAndAneuploidyScore_092817.txt"
) %>%
  replace(is.na(.), 0) %>%
  select(-c("Type", "Aneuploidy Score")) %>%
  mutate(Sample = str_replace_all(Sample, "-", "\\.")) %>%
  column_to_rownames("Sample") %>%
  mutate_all(~ replace(., . == 1, 2)) %>%
  mutate_all(~ replace(., . == 0, 1)) %>%
  mutate_all(~ replace(., . == -1, 0))
```
Create the folds to be used
```{r}
full_data <- merge(read.csv(
    paste0(
      rna_data_path,
      "tpm",
      "_soi.csv"
    ),
    row.names = 1
  ),
  chr_cnv,
  by = "row.names") 

folds <- createFolds(full_data[["1p"]], k =2, list = TRUE, returnTrain = FALSE)

# Get the indices of all folds in a list
fold_indices <- combine_all_folds(folds)
```


```{r}
# Get the parameters from stored Parameters file
parameters <- read.csv("Data/CIN_Features/XGB_cat_parameters.csv")

# Create the empty dataframe that will store the predictions from each model
predictions_df <- data.frame(
  matrix(
    ncol = nrow(parameters),
    nrow = length(folds$Fold1)*length(folds)
  )
)
colnames(predictions_df) <- paste0("pred_", parameters$Feature)
rownames(predictions_df) <- as.factor(fold_indices)

# Get the true fold labels
fold_labels <- full_data %>% 
  select(all_of(intersect(parameters$Feature, colnames(.)))) %>% 
  mutate(index = as.factor(row_number()),
         sort_order = match(rownames(.), fold_indices)) %>%
  rename_with(~ paste0("act_", .)) %>%
  column_to_rownames("act_index") %>% 
  arrange(act_sort_order)

# merge the fold labels with the predictions dataframe
predictions_df <- merge(predictions_df, fold_labels, by = "row.names") %>% 
  arrange(act_sort_order) %>% 
  column_to_rownames("Row.names") %>% 
  select(-act_sort_order)

```


```{r}
# Loop through the parameters and create the models
for (index in 1:length(distinct(parameters$Feature))) {
  
  # select the parameters and weights corresponding to the feature (index)
  selected_parameters <- parameters[index, ]
  
  selected_feature <- selected_parameters$Feature
  selected_rna_set <- selected_parameters$RNA_set
  selected_trees <- as.numeric(selected_parameters$Trees)
  selected_eta <- selected_parameters$Eta
  selected_gamma <- selected_parameters$Gamma
  selected_depth <- selected_parameters$Max_depth
  selected_weights <- as.numeric(selected_parameters[c("Weight.loss", "Weight.normal", "Weight.gain")])
  selected_min_child <- 1
  selected_seed <- 99
  
  cat(
    "\n Selected Parameters: \n",
    "Feature: ", selected_feature, "\n",
    "RNA Set: ", selected_rna_set, "\n",
    "Trees: ", selected_trees, "\n",
    "Eta: ", selected_eta, "\n",
    "Gamma: ", selected_gamma, "\n",
    "Max Depth: ", selected_depth, "\n",
    "Weights: ", selected_weights, "\n",
    "Min Child: ", selected_min_child, "\n",
    "Seed: ", selected_seed, "\n"
  )
  
  # Load the RNA set corresponding to the selected RNA set for the specific feature
  rna_selection_name <- rna_list[[selected_rna_set]]
  rna_set <- read.csv(
    paste0(
      rna_data_path,
      rna_selection_name,
      "_soi.csv"
    ),
    row.names = 1
  )
  print(head(rna_set[, 1:5]))
  
  # Merge the RNA set with the CNV data to create the full data set
  full_df <- merge(rna_set,
                   chr_cnv,
                   by = "row.names"
  )
  
  # Identify the X and y variables
  y <- as.integer(full_df[[selected_feature]])
  X <- full_df %>% select(-c("Row.names", colnames(chr_cnv)))
  
  # Assign the weights for the model
  train_y_factor <- factor(y, levels = c(0, 1, 2))
  weights <- as.numeric(feature_digit_function(train_y_factor))
  
  # Create the xgb data
  xgb_data <- xgb.DMatrix(data = as.matrix(X), label = y, weight = weights)
  
  # Create the model
  xgb_model <- xgb.cv(
    data = xgb_data,
    nrounds = selected_trees,
    objective = "multi:softmax",
    eval_metric = "mlogloss",
    early_stopping_rounds =50,
    folds = folds,
    max_depth = selected_depth,
    min_child_weight = selected_min_child,
    eta = selected_eta,
    gamma = selected_gamma,
    num_class = 3,
    print_every_n = 10,
    prediction = TRUE
  )
  
  # Store the predictions in the corresponding column
  predictions_df[[paste0("pred_", selected_feature)]] <- xgb_model$pred[, 1]
  
}
```




Save the predictions to a csv file
```{r}
write.csv(predictions_df, "Data/CIN_Features/XGB_base_predictions.csv")
```
















