---
title: "Cancer Specific SOI RNA set creation"
output: html_document
date: "2024-06-30"
Note: This script is for the generation of RNA sets that are cancer specific.
---


1.  SETUP

1.1. SETUP

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project")
```

1.2. Load the necessary libraries
```{r}
library(dplyr)
library(tidyverse) 
library(ggrepel)
library(data.table)

```

1.3. Reusable functions
```{r}
extract_element <- function(strings, index) {
  # Split each string by "." and extract the third element
  element_list <- sapply(strsplit(strings, "\\."), function(x) x[index])
  return(element_list)
}
```

1.4. Load the necessary data
```{r}
# TCGA RNA data
data_folder <- "Data/RNA_data/Gen_model_input/Full"

# TCGA metadata
meta_data_folder <- "Data/Other/TCGA_meta"
tss_code_file <- read_tsv(file.path(meta_data_folder, "tissueSourceSite.tsv"),show_col_types = FALSE, na = character())
abbreviations_file <- read_tsv(file.path(meta_data_folder, "diseaseStudy.tsv"), show_col_types = FALSE)

```

Construct the new folder
```{r}
for (cancer in unique(abbreviations_file[['Study Abbreviation']])) {
  if (dir.exists(paste0("Data/Cancer_specific_data/Model_input/RNA/", cancer))) {
    next
  }
  new_folder <- paste0("Data/Cancer_specific_data/Model_input/RNA/", cancer)
  dir.create(new_folder)
}

```


```{r}
# Loop over the RNA csv sets in the folder 
for (set in list.files(data_folder, pattern = ".csv")) {
  cat("\n\n Set: ", set, "\n")
  # Load the TCGA RNA data
  rna_set <- read.csv(file.path(data_folder, set), header = TRUE, sep = ",", row.names = 1) %>% 
    mutate(Cancer_type = extract_element(rownames(.),2)) %>% 
    rownames_to_column("Sample") %>%
    left_join(
      tss_code_file %>% 
        select("TSS Code", "Study Name"), 
      by = c("Cancer_type" = "TSS Code")
      ) %>% 
    left_join(abbreviations_file, by = "Study Name") %>% 
    select(-c("Study Name", "Cancer_type")) %>%
    select("Study Abbreviation", everything()) %>% 
    rename("Cancer" = "Study Abbreviation") %>% 
    column_to_rownames("Sample")
  
  # Loop over the cancer types
  for (cancer in unique(rna_set$Cancer)) {
    cat("\n Cancer: ", cancer, "\n")
    # Filter the RNA set for the cancer type
    cancer_rna_set <- rna_set %>% 
      filter(Cancer == cancer) 
    
    if (nrow(cancer_rna_set) == 0) {
      next
    }
    cat("\t Number of samples: ", nrow(cancer_rna_set), "\n")
    
    # Save the RNA set
    write.csv(cancer_rna_set,
              paste0("Data/Cancer_specific_data/Model_input/RNA/",
                     cancer, "/",
                     set),
              row.names = TRUE)
  }
}
```


