# This script is used to assess the hyperparameters for the cancer-specific meta learner models
# using the individual hyperparameter tuning data for each feature generated by parallel prcoessing

library(dplyr)
library(knitr)
library(dplyr)
library(ggplot2)

feature_order <- c(
  "1p", "1q", "2p", "2q", "3p",
  "3q", "4p", "4q", "5p", "5q",
  "6p", "6q", "7p", "7q", "8p",
  "8q", "9p", "9q", "10p", "10q",
  "11p", "11q", "12p", "12q", "13q",
  "14q", "15q", "16p", "16q", "17p",
  "17q", "18p", "18q", "19p", "19q",
  "20p", "20q", "21q", "22q", "peri_1",
  "peri_2", "peri_3", "peri_4", "peri_5",
  "peri_7", "peri_8", "peri_9", "peri_10",
  "peri_16_1", "peri_16_2", "peri_17", "peri_20",
  "peri_22_3", "ai1", "loh_hrd", "lst1"
)

hyper_folder <- file.path("/hpc/shared/prekovic/dhaynessimmons/data/Cancer_specific_data/Model_input/Parameters/Hyperparameters/")


for (cancer_folder in list.files(hyper_folder)) {
  cat(cancer_folder, "\n\n")
  individual_folder <- file.path(hyper_folder, cancer_folder, "individual_features")

  # Create the empty df
  full_hyperparams <- data.frame()

  for (file in list.files(individual_folder, pattern = "*.csv")) {
    # cat(file, "\n")

    # Read the file
    current_file <- read.csv(file.path(individual_folder, file))
    print(head(current_file))

    # Add the df to the full df
    full_hyperparams <- rbind(full_hyperparams, current_file) %>%
      mutate(Feature = factor(Feature, levels = feature_order)) %>%
      arrange(Feature)
  }

  best_hyperparameters <- full_hyperparams %>%
    group_by(Feature) %>%
    slice_min(Test_result, n = 1, with_ties = FALSE) %>%
    select(Feature, Trees, Max_depth, Eta, Gamma, Child_weight)

  # Save the best hyperparameters
  write.csv(
    best_hyperparameters,
    file.path(hyper_folder, cancer_folder, "meta_hyperparameters.csv"),
    row.names = FALSE
  )

  # Save teh full hyperparameters
  write.csv(
    full_hyperparams,
    file.path(hyper_folder, cancer_folder, "meta_full.csv"),
    row.names = FALSE
  )

  # Delete all the individual files from the folder
  file.remove(file.path(individual_folder, list.files(individual_folder)))
}
