---
  title: "TCGA_CIN_FEATURES"
format: html
editor: visual
Notes: This script is intended to do some exploration of the samples in the CIN Features in the TCGA PanCan datasets.
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project")
```

## Load the libraries

## Load the libraries

```{r}
library(dplyr)
library(mltools)
library(knitr)
library(tidyverse)
library(data.table)
library(ggpubr)
library(psych)
```

Re-usable functions

```{r}
extract_element <- function(strings, index) {
  # Split each string by "." and extract the third element
  element_list <- sapply(stringr::str_split(strings, "\\-"),
                         function(x) x[index])
  return(element_list)
}
```

Import data

```{r}
ori_hrd <- read_tsv("Data/CIN_Features/TCGA.HRD_withSampleID.txt")
```

HRD Scores

```{r}
t_hrd <- t(ori_hrd) 
first_hrd <- t_hrd
colnames(first_hrd) <- t_hrd[1, ]
hrd <- first_hrd[-1,0:3] # removal of the HRD total (just the sum of the previous columns)

```

Visualisations of the relationships

```{r}
dist <- dist(hrd)
dist_matrix <- as.matrix(dist)

# Produce the MDS object.
mds <- cmdscale(dist)

# Convert the MDS object to a dataframe with additional features
mds_df <- as.data.frame(mds) %>% 
  dplyr::mutate(cancer_type = extract_element(rownames(hrd), 2),
         sample_type = extract_element(rownames(hrd), 4),
         synergy_type = paste(cancer_type, sample_type, sep = "-"))

# Create the plots of the MDS.
sample_mds <- ggpubr::ggscatter(mds_df, x = "V1", y = "V2",
  color = "sample_type", # Colour based on the sample type
  size = 1,
  repel = TRUE
)

cancer_mds <- ggpubr::ggscatter(mds_df, x = "V1", y = "V2", 
  color = "cancer_type", # Colour based on the cancer type
  size = 1,
  repel = TRUE) + theme(legend.position = "none")


synergy_mds <- ggpubr::ggscatter(mds_df, x = "V1", y = "V2", 
          color = "cancer_type", # Colour based on the synergy between the cancer and sample type
          shape = "sample_type",
          size = 1,
          repel = TRUE) +
  theme(legend.position = "none")
  # coord_cartesian(xlim = c(-35, 20),
  #                 ylim = c(-25,25))
```

The plots don't indicate to any means of separating the data via the arm aneuploidies