---
title: "Aniek_Analysis"
output: html_document
date: "2024-04-23"
---

```{r}
library(dplyr)
library(plyr)
library(knitr)
library(tidyverse)
library(edgeR)
library(limma)
library(data.table)
library(ggpubr)
```


```{r}
df <- read.csv("/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project/DGEA_ALLGENES_BYTISSUE_XPRSS_TBL.csv")
study <- read.csv("/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project/Data/Other/TCGA_meta/diseaseStudy.tsv", sep = "\t")
```


The genes of interest are CBX5/1/3, CHAF1A and, EHMT2 makin
```{r}

link <- df %>% left_join(study,
                         by = c("Tissue" = "Study.Abbreviation"))
filtered_df <- link[link$Genes %in% c("CBX1", "CBX3", "CBX5", "CHAF1A", "EHMT2"),] %>% 
  select(-"X")

write.csv(filtered_df, "Aniek_data.csv")
```

Assess which of these genes is DE in each of the tumour types
```{r}
for (cancer in unique(filtered_df$Tissue)){
  use <- filtered_df %>% 
    filter(Tissue == cancer)
  assign(paste0(cancer,"_df"), use)
  
}
```






