---
title: "Gene Subset analysis"
output: html_document
date: "2024-01-18"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project")
```
Load the libraries
```{r}
library(dplyr)
library(pheatmap)
library(reshape2)
library(tidyverse)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
``` 

Load other options
```{r}
getOption("max.print")
```


1. Load the data
```{r}
first <- read.csv("Data/RNA_Data/Genes_of_Interest_RNA_df.csv")

print(head(first))
```


2. Sample the data 

```{r}
set.seed(123)


Sample_data <- first[sample(1:10000, 100),]
print(head(Sample_data))
```


```{r}
column_names <- colnames(Sample_data)[-1]
cor_data <- Sample_data[,column_names]

print(head(cor_data))
```


3. Correlate the genes in the data

```{r}
gene_cor_pear <- cor(cor_data, method = "pearson")

# gene_cor_spear <- cor(cor_data, method = "spearman")
```


```{r}
gene_cor_pear[is.na(gene_cor_pear)] <- 0
Heatmap(gene_cor_pear, 
         rect_gp = gpar(col = "black", lwd = 0.1),
        col = colorRamp2(c(-1, 0, 1), c("#20c712", "white", "purple2")),
        row_names_gp = gpar(fontsize = 4),
        column_names_gp = gpar(fontsize = 4))

```
















