---
title: "GTEx DF Creation Test"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/Dyll/Documents/Education/VU_UVA/Internship/Epigenetics/Janssen_Group-UMCUtrecht/Main_Project")
```

```{r}
library(dplyr)
library(broom)
library(knitr)
library(coin)
library(ggpubr)
library(rstatix)
library(tidyverse)
library(jmuOutlier)
library(paletteer)
```


```{r}
library(readr) # for read_csv
library(dplyr) # for data manipulation

# Reading the full RNA GTEx dataset
GTEx_Samp_df <- read_csv("../../../Data/RNA_Data/GTEx_RNA/Raw_GTEx_RNA_Norm.csv", col_types = cols())

# Reading the first RNA GTEx metadata dataset that contains the phenotype of the subject
GTEx_meta_df <- read_csv("../../../Data/RNA_Data/GTEx_RNA/GTEx_RNA_Subject_meta.csv", col_types = cols())

# Reading the second metadata dataset that contains the rest of the metadata for the subjects
GTEx_Annotations_df <- read_csv("../../../Data/RNA_Data/GTEx_RNA/GTEx_Annotations.csv", col_types = cols())

# Get the SUBJIDS that correspond to the samples to be used
Healthy_Subjects <- unique(GTEx_meta_df %>% filter(DTHHRDY %in% c(1, 2, 3, 0)) %>% pull(SUBJID))

# Get the column names from the full RNA GTEx dataset, starting from the 4th column
cols <- colnames(GTEx_Samp_df)[-c(1:3)]

# Get the columns that should be dropped from the dataset
cols_to_drop <- cols[!substr(cols, 1, 10) %in% Healthy_Subjects]

# Create a new DataFrame without the columns to be dropped
GTEx_Healthy_df <- GTEx_Samp_df %>% select(-one_of(cols_to_drop))

# Get the Sample IDs that correspond to the samples to be used
selected_samples <- GTEx_Annotations_df %>% filter(SMRIN >= 6) %>% pull(SAMPID)
selected_samples_list <- c("Description", selected_samples)

# Create a DataFrame with the columns to be used
GTEx_Viable_Healthy <- GTEx_Healthy_df %>% select(all_of(selected_samples_list))

GTEx_Viable_Healthy <- GTEx_Viable_Healthy %>% 
  group_by(Description) %>%
  summarise_all(mean, na.rm = TRUE) %>%
  rownames_to_column(var = "Description")

GTEx_Viable_Healthy$Description <- toupper(GTEx_Viable_Healthy$Description)

# Get the genes that are used in the TCGA PanCan Dataset
TCGA_Pancan_df <- read_csv("../../../Data/RNA_Data/TCGA_mRNA_Norm.csv", col_types = cols(.default = "c"), col_select = "gene")

# Get the Genes of Interest that are used in the TCGA PanCan
SoI_list <- read_csv('../../../Data/RNA_Data/Genes_of_Interest_RNA_Data_df.csv', col_types = cols(), n_max = 0) %>% colnames()
SoI_list <- toupper(SoI_list)

# Create the dataframe for the GTEx using the genes of interest.
GTEx_SOI_df <- GTEx_Viable_Healthy %>% 
  filter(Description %in% SoI_list) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "SampleID")

GTEx_SOI_df[-1] <- lapply(GTEx_SOI_df[-1], as.numeric)

# Similarly, create GTEx_Cntrl_df for controls, and follow with the control sets matching process.

# Note: The `sample` function in R can be used in place of `random.sample` for selecting random genes.
# The R script may require adjustments for file paths and specific operations (e.g., random sampling, saving files).

```

